// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eulalia_backend.Infrastructure.Data;

#nullable disable

namespace eulalia_backend.Infrastructure.Migrations
{
    [DbContext(typeof(EulaliaContext))]
    [Migration("20250805140850_AddBiometriaCiudadano")]
    partial class AddBiometriaCiudadano
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eulalia_backend.Domain.Entities.Afiliacion", b =>
                {
                    b.Property<int>("Afiliacion_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("afiliacion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Afiliacion_Id"));

                    b.Property<int?>("BlockchainTxId")
                        .HasColumnType("integer")
                        .HasColumnName("blockchaintxid");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cedula");

                    b.Property<bool>("EsUltima")
                        .HasColumnType("boolean")
                        .HasColumnName("esultima");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAfiliacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaafiliacion");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("text")
                        .HasColumnName("motivocancelacion");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer")
                        .HasColumnName("organizacionid");

                    b.Property<int?>("UsuarioAprobador")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioaprobador");

                    b.HasKey("Afiliacion_Id")
                        .HasName("pk_afiliacion");

                    b.ToTable("afiliacion", (string)null);
                });

            modelBuilder.Entity("eulalia_backend.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("auditoriaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditoriaId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.HasKey("AuditoriaId")
                        .HasName("pk_auditoria");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("eulalia_backend.Domain.Entities.BiometriaCiudadano", b =>
                {
                    b.Property<int>("BiometriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("biometriaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BiometriaId"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cedula");

                    b.Property<string>("EstadoVerificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estadoverificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecharegistro");

                    b.Property<string>("HashTemplate")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hashtemplate");

                    b.Property<byte[]>("TemplateCifrado")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("templatecifrado");

                    b.HasKey("BiometriaId")
                        .HasName("pk_biometrias_ciudadano");

                    b.ToTable("biometrias_ciudadano", (string)null);
                });

            modelBuilder.Entity("eulalia_backend.Domain.Entities.Blockchain", b =>
                {
                    b.Property<int>("BlockchainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("blockchainid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BlockchainId"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechatransaccion");

                    b.Property<string>("HashTransaccion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashtransaccion");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipotransaccion");

                    b.HasKey("BlockchainId")
                        .HasName("pk_blockchain");

                    b.ToTable("blockchain", (string)null);
                });

            modelBuilder.Entity("eulalia_backend.Domain.Entities.Ciudadano", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("text")
                        .HasColumnName("cedula");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<DateTime?>("Fecha_Nacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Cedula")
                        .HasName("pk_ciudadano");

                    b.ToTable("ciudadano", (string)null);
                });

            modelBuilder.Entity("eulalia_backend.Domain.Entities.Organizacion", b =>
                {
                    b.Property<int>("Organizacion_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("organizacion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Organizacion_Id"));

                    b.Property<int?>("Codigo_Canton")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_canton");

                    b.Property<int?>("Codigo_Parroquia")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_parroquia");

                    b.Property<int?>("Codigo_Provincia")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_provincia");

                    b.Property<string>("Estado_Validacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_validacion");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Responsable_Cedula")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("responsable_cedula");

                    b.Property<string>("Tipo_Organizacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_organizacion");

                    b.HasKey("Organizacion_Id")
                        .HasName("pk_organizacion");

                    b.HasIndex("Responsable_Cedula")
                        .HasDatabaseName("ix_organizacion_responsable_cedula");

                    b.ToTable("organizacion", (string)null);
                });

            modelBuilder.Entity("eulalia_backend.Domain.Entities.Parametrosistema", b =>
                {
                    b.Property<string>("ParametroId")
                        .HasColumnType("text")
                        .HasColumnName("parametroid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seccion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("ParametroId")
                        .HasName("pk_parametrosistema");

                    b.ToTable("parametrosistema", (string)null);
                });

            modelBuilder.Entity("eulalia_backend.Domain.Entities.Provincia", b =>
                {
                    b.Property<int>("Codigo_Provincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("codigo_provincia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo_Provincia"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Codigo_Provincia")
                        .HasName("pk_provincia");

                    b.ToTable("provincia", (string)null);
                });

            modelBuilder.Entity("eulalia_backend.Domain.Entities.RolUsuario", b =>
                {
                    b.Property<int>("Rol_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Rol_Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Rol_Id")
                        .HasName("pk_rolusuario");

                    b.ToTable("rolusuario", (string)null);
                });

            modelBuilder.Entity("eulalia_backend.Domain.Entities.SSI", b =>
                {
                    b.Property<int>("Ssi_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ssi_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Ssi_Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cedula");

                    b.Property<string>("Credencial_Digital")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("credencial_digital");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha_Emision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime?>("Fecha_Revocacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_revocacion");

                    b.HasKey("Ssi_Id")
                        .HasName("pk_ssi");

                    b.ToTable("ssi", (string)null);
                });

            modelBuilder.Entity("eulalia_backend.Domain.Entities.SolicitudOrganizacion", b =>
                {
                    b.Property<int>("Solicitud_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Solicitud_Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecharevision");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechasolicitud");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("Organizacion_Id")
                        .HasColumnType("integer")
                        .HasColumnName("organizacion_id");

                    b.Property<int?>("UsuarioRevisor")
                        .HasColumnType("integer")
                        .HasColumnName("usuariorevisor");

                    b.HasKey("Solicitud_Id")
                        .HasName("pk_solicitudorganizacion");

                    b.HasIndex("Organizacion_Id")
                        .HasDatabaseName("ix_solicitudorganizacion_organizacion_id");

                    b.ToTable("solicitudorganizacion", (string)null);
                });

            modelBuilder.Entity("eulalia_backend.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Usuario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Usuario_Id"));

                    b.Property<string>("Cedula_Ciudadano")
                        .HasColumnType("text")
                        .HasColumnName("cedula_ciudadano");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contrasena");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("Rol_Id")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.HasKey("Usuario_Id")
                        .HasName("pk_usuario");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("eulalia_backend.Domain.Entities.Organizacion", b =>
                {
                    b.HasOne("eulalia_backend.Domain.Entities.Ciudadano", "Responsable")
                        .WithMany()
                        .HasForeignKey("Responsable_Cedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organizacion_ciudadano_responsable_cedula");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("eulalia_backend.Domain.Entities.SolicitudOrganizacion", b =>
                {
                    b.HasOne("eulalia_backend.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("Organizacion_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_solicitudorganizacion_organizacion_organizacion_id");

                    b.Navigation("Organizacion");
                });
#pragma warning restore 612, 618
        }
    }
}
